### Список всех товаров
GET /api/product/getall HTTP/1.1
Host: localhost:7000

### Получить один товар
GET /api/product/getone/12345 HTTP/1.1
Host: localhost:7000

### Создать новый товар
POST /api/product/create HTTP/1.1
Host: localhost:7000

### Обновить товар
PUT /api/product/update/12345 HTTP/1.1
Host: localhost:7000

### Удалить товар
DELETE /api/product/delete/12345 HTTP/1.1
Host: localhost:7000